name: Rsgen CI / CD pipeline
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v1
      - name: Setup node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: '14.16'
      - name: Install global dependencies
        run: npm i typescript@4.2.2 -g
      - name: Install local dependencies
        run: npm i
      - name: Compile Typescript files
        run: tsc
      - name: Execute tests sets
        run: npm run ci:coverage
      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./reports/coverage/lcov.info
      - name: Delete unpackaged files
        run: rm -rf ./.github && rm -rf ./src && rm -rf ./test && rm -f tsconfig.json && rm -f ROADMAP.md
      - name: Publish package on NPM registery
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}